import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-svw h-svh m-0`}>
        <div className="flex items-center justify-between mb-10">
          <Navbar></Navbar>
          <Link href={"/"} className="grow">
            <h1 className="font-open-sans text-[38px] font-extrabold text-brand text-center block w-fit m-auto  ">
              Genesis
            </h1>
          </Link>
        </div>
        <main className="w-full max-w-[1200px] m-auto pl-3 pr-3">
          {children}
        </main>
      </body>
    </html>
  );
}
